trigger: none


pool:
  vmImage: 'ubuntu-latest'
  demands:
    - npm
    - node.js
variables:
  - group: 'rk-dev-blob-CI'
  - group: 'rk-dev-redis-CI'
  - group: 'rk-dev-mongo-CI'

steps:
  - task: NodeTool@0
    displayName: "Use Node version"
    inputs:
      versionSpec: 10.14.1

  - task: Npm@1
    displayName: "npm install"
    inputs:
      command: "install"
      customRegistry: "useFeed"
      customFeed: "a14d7aa6-4fa9-4959-ad6b-13014feb8621/977b63e8-b132-441d-88a2-bd909ff9d3c2"

  - task: Npm@1
    displayName: "npm run build"
    inputs:
      command: "custom"
      customCommand: "run build"
      verbose: true
      customRegistry: "useFeed"
      customFeed: "a14d7aa6-4fa9-4959-ad6b-13014feb8621/977b63e8-b132-441d-88a2-bd909ff9d3c2"

  - task: Npm@1
    displayName: "npm run test"
    inputs:
      command: "custom"
      customCommand: "run test"
      customRegistry: "useFeed"
      customFeed: "a14d7aa6-4fa9-4959-ad6b-13014feb8621/977b63e8-b132-441d-88a2-bd909ff9d3c2"
      verbose: true
    env:
      BLOB_ACCOUNT: "$(BLOB_ACCOUNT)"
      BLOB_ACCOUNT_KEY: "$(BLOB_ACCOUNT_KEY)"
      MONGO_DB_NAME: "$(MONGO_DB_NAME)"
      MONGO_DB_URI: "$(MONGO_DB_URI)"
      MONGO_PASSWORD: "$(MONGO_PASSWORD)"
      MONGO_USER: "$(MONGO_USER)"
      REDIS_HOST: "$(REDIS_HOST)"
      REDIS_PORT: "$(REDIS_PORT)"
      REDIS_PASSWORD: "$(REDIS_PASSWORD)"
