trigger:
  batch: true
  branches:
    include:
      - master
      - release/*
  paths:
    include:
      - utilities/*

pool:
  vmImage: 'ubuntu-latest'
  demands:
    - npm
    - node.js

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 10.14.1
    displayName: "Use Node version"

  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: 'utilities'
      customRegistry: 'useFeed'
      customFeed: 'a14d7aa6-4fa9-4959-ad6b-13014feb8621/977b63e8-b132-441d-88a2-bd909ff9d3c2'

  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: 'utilities'
      customCommand: 'run build'
      customRegistry: 'useFeed'
      customFeed: 'a14d7aa6-4fa9-4959-ad6b-13014feb8621/977b63e8-b132-441d-88a2-bd909ff9d3c2'
      verbose: true

  - script: |
      #Copy node package files to bin directory
      cp $(Build.SourcesDirectory)/utilities/package*.json $(Build.SourcesDirectory)/bin
    displayName: "move package.json to bin"

  - task: Npm@1
    displayName: "npm publish"
    inputs:
      command: 'publish'
      workingDir: 'bin'
      publishRegistry: 'useFeed'
      publishFeed: 'a14d7aa6-4fa9-4959-ad6b-13014feb8621/977b63e8-b132-441d-88a2-bd909ff9d3c2'
