name: $(BuildID)

trigger:
  branches:
    include:
      - master
      - release
      - feat*
  paths:
    include:
      - 'basic-express-app/*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Hello from 'a'"