name: starter-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12 # ${{ matrix.node-version }}
    
    # Rush
    - name: Checking for missing change logs
      run: node common/scripts/install-run-rush.js change -v

    - name: Installing
      run: node common/scripts/install-run-rush.js install

    - name: Building
      run: node common/scripts/install-run-rush.js rebuild --verbose

    # - name: Install
    #   run: npm i -g lerna
    # - name: Install
    #   run: yarn bootstrap

    # - name: Build
    #   run: yarn build

    # - name: Git Identity
    #   run: |
    #     git config --global user.name 'robk-dev'
    #     git config --global user.email 'robk-dev@users.noreply.github.com'
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Versionup bump
    #   run: |
    #     echo "add auto version bump here"

    # - name: Set current CHANGELOG to output
    #   id: changelog
    #   shell: bash -ex {0}
    #   run: |
    #     version=$(node -p 'require("./lerna.json").version')
    #     echo "::set-output name=version::${version}"

    # - name: Create Pull Request
    #   id: cpr
    #   uses: peter-evans/create-pull-request@v2
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     commit-message: "Update v${{ steps.changelog.outputs.version }}"
    #     committer: GitHub <noreply@github.com>
    #     author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
    #     title: 'v${{ steps.changelog.outputs.version }}'
    #     body: |
    #       ## v${{ steps.changelog.outputs.version }}
    #       ### Breaking Changes
    #       - [ ] TODO
    #       ### Features
    #       - [ ] TODO
    #       ### Bug Fixes
    #       - [ ] TODO
    #     labels: "Type: Release"
    #     branch: "release/next"
    #     request-to-parent: false
    # - name: Check outputs
    #   run: |
    #     echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
    #     echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
